# Generated by Django 2.2.28 on 2025-03-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishcovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/recipe_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/profile_images'),
        ),
    ]
